# Generated by Django 4.1 on 2022-08-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_newuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='JSESSIONID',
            field=models.CharField(default=0, max_length=60, verbose_name='cook-JSESSIONID'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='route',
            field=models.CharField(default=0, max_length=80, verbose_name='cook-route'),
        ),
    ]
