# Generated by Django 4.1 on 2022-08-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_newuser_jsessionid_newuser_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='JSESSIONID',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='route',
        ),
    ]
